version: '3.9.1'
services:
  frontend:
    env_file: ./config/dev.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/widgets_and_gadgets_backend